    <!-- Заголовок и контент -->


    <div class="content_price">
        <div class="container">
            <div class="row">
                <h1 class="name_price">Схема проезда</h1>
                <span class="cherta_ind hidden-xs"></span>
            </div>
        </div>
    </div>


    <!-- Карта -->

    <div class="container">
        <div class="row">
            <div class="map">

                <script type="text/javascript" charset="utf-8" async
                        src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=t3W8U-dHCLy2t2wM_oVfRtwrA7sImlwZ&width=100%&height=550&lang=ru_RU&sourceType=constructor&scroll=true"></script>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="contact_list">
                <h class="map_text_b">Наши контакты:</h>
                <p class="map_text_r">г. Ярославль, ул. Свободы, д.46/3 (территория Казарм)</p>
                <p class="map_text_r">тел.: +7 (4852) 33-72-00</p>
                <p class="map_text_r">e-mail: levelup76@yandex.ru</p>
                <br>
                <h class="map_text_b">Мы в социальных сетях:</h>
                <p class="map_text_social">
                    <a href="https://vk.com/levelup76" target="_blank"><i class="fa fa-vk"></i></a>
                    <a href="https://www.instagram.com/levelup76" target="_blank"><i class="fa fa-instagram"></i></a>

                    <a href="https://www.facebook.com/levelupy" target="_blank"><i class="fa fa-facebook"></i></a>
                </p>
            </div>
        </div>
    </div>
    <br>