
    <!-- Заголовок и контент -->
    <div class="content_price">
        <div class="container">
            <div class="row">
                <div class="name_price">Детские праздники в Level<span class="UP">UP</span>!</div>
                <span class="cherta_ind hidden-xs"></span>
            </div>
        </div>
    </div>
    <!-- Контент -->
    <!-- Дети -->
    <div class="children_content">
        <div class="container">
            <div class="row">


                <!-- Карусель фотографий -->
                <div id="children_block" class="carousel slide" data-ride="carousel">
                    <!-- Индикаторы -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#children_block" data-slide-to="1"></li>
                        <li data-target="#children_block" data-slide-to="2"></li>
                        <li data-target="#children_block" data-slide-to="3"></li>
                        <li data-target="#children_block" data-slide-to="4"></li>
                        <li data-target="#children_block" data-slide-to="5"></li>
                    </ol>

                    <!-- Слайды и подписи -->
                    <div class="carousel-inner">
                        <div class="active item"> <img src="/img/child_celeb_01.jpg" class="img-responsive" alt="Responsive image"> </div>
                        <div class="item">  <img src="/img/child_celeb_02.jpg" class="img-responsive" alt="Responsive image"> </div>
                        <div class="item">  <img src="/img/child_celeb_03.jpg" class="img-responsive" alt="Responsive image"> </div>
                        <div class="item">  <img src="/img/child_celeb_04.jpg" class="img-responsive" alt="Responsive image"> </div>
                        <div class="item">  <img src="/img/child_celeb_05.jpg" class="img-responsive" alt="Responsive image"> </div>
                        <div class="item">  <img src="/img/child_celeb_06.jpg" class="img-responsive" alt="Responsive image"> </div>
                    </div>

                    <!-- Контроллеры -->
                    <a class="left carousel-control" href="#children_block" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#children_block" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>

                <p class="chil_text">Для любого человека День Рождения - это особенный день. День, когда сбываются мечты, день ожидания желанных подарков, день приятных сюрпризов и неожиданностей. Но больше всего этого дня ждут дети. Хочется, чтобы этот день запомнился надолго, чтобы он был особенным, не похожим на другие.</p>
                <p class="chil_text">Мы хотим предложить Вам провести этот особенный день с нами, в батутном центре "Level Up". Здесь сбываются мечты (кто из нас в детстве не хотел допрыгнуть до звезд?), дарятся желанные подарки, ждет масса приятных сюрпризов и неожиданностей, улыбок и смеха.</p>
                <p class="chil_text">Позитивные ведущие, активная программа праздника с увлекательными заданиями и препятствиями, море позитива и положительных эмоций - и это все здесь!</p>
                <p class="chil_text">Будем рады разделить радость праздника с вашими детьми и конечно же с Вами! </p>
                <p class="chil_text">Подробнее - 8(920) 130-41-23, Наталья.</p>

            </div>
        </div>
    </div>

    <!-- Конец блока Дети -->
    <br>