    <!-- Заголовок и контент -->

    <div class="content_price">
        <div class="container">
            <div class="row">
                <h1 class="name_price">Цены и действующие акции</h1>
                <span class="cherta_ind hidden-xs"></span>
            </div>
        </div>
    </div>


    <br>

    <!-- Контент -->


    <!-- Таблица -->
    <div class="cont_price">
        <div class="container">
            <div class="row">


                <table class="table_posit">
                    <caption id="tab-h">Разовые посещения</caption>
                    <thead class="tab-block-b">
                    <tr>
                        <th id="tab_b"></th>
                        <th id="tab_b"><h4 id="tab-b-n">Будние дни с 14:00 до 18:00</h4></th>
                        <th id="tab_b"><h4 id="tab-b-n">Будние дни после 18:00,<br> выходные, праздничные<br>с 10:00 до 22:00</h4></th>
                    </tr>
                    </thead>
                    <tbody class="tab-block">
                    <tr>
                        <td id="tab_n_n">Взрослый тариф/1 занятие</td>
                        <td id="tab_n">200 <i class="fa fa-rub" aria-hidden="true"></i> <button type="button" class="btn btn-secondary" onclick="window.location.href='https://pay.erpico.ru/pay.php?partner=1&amount=20000&refId=1&text=LevelUp разовое посещение в будний день'">Купить</button></td>
                        <td id="tab_n">400 <i class="fa fa-rub" aria-hidden="true"></i> <button type="button" class="btn btn-secondary" onclick="window.location.href='https://pay.erpico.ru/pay.php?partner=1&amount=40000&refId=2&text=LevelUp разовое посещение в выходной день'">Купить</button></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">Взорслый + ребенок/1 занятие</td>
                        <td id="tab_n">300 <i class="fa fa-rub" aria-hidden="true"></i>  <button type="button" class="btn btn-secondary" onclick="window.location.href='https://pay.erpico.ru/pay.php?partner=1&amount=30000&refId=1&text=LevelUp взрослый+ребенок в будний день'">Купить</button></td>
                        <td id="tab_n">600 <i class="fa fa-rub" aria-hidden="true"></i>  <button type="button" class="btn btn-secondary" onclick="window.location.href='https://pay.erpico.ru/pay.php?partner=1&amount=60000&refId=1&text=LevelUp взрослный+ребенок в выходной день'">Купить</button></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">«Вместе веселее» (20:00-22:00)<br>1 занятие / 2 человека</td>
                        <td colspan="2" id="tab_n">500 <i class="fa fa-rub" aria-hidden="true"></i>  <button type="button" class="btn btn-secondary" onclick="window.location.href='https://pay.erpico.ru/pay.php?partner=1&amount=50000&refId=1&text=LevelUp JAM в будний день'">Купить</button></td>
                       
                    </tr>

                    <tr>
                        <td id="tab_n_n">«Мама+Малыш»<br>1 занятие / 2 человека</td>
                        
                        <td colspan="2" id="tab_n">300 <i class="fa fa-rub" aria-hidden="true"></i>  <button type="button" class="btn btn-secondary" onclick="window.location.href='https://pay.erpico.ru/pay.php?partner=1&amount=30000&refId=1&text=LevelUp JAM в будний день'">Купить</button></td>

                    </tr>

                    <tr>
                        <td colspan="3"><hr id="cherta_tab"></td>
                    </tr>
                    </tbody>
                </table>

                <div class="container">
                    <div class="row" id="tab_text_down">
                <span>Для студентов и школьников акция «ВМЕСТЕ ВЕСЕЛЕЕ» действует с 18.00<br>
                (при предъявлении документа, подтверждающего возраст/документа с места учёбы)
                </span>
                    </div>
                </div>

                <table class="table_posit">
                    <caption id="tab-h">Абонементы на свободное посещение</caption>
                    <thead class="tab-block-b">
                    <tr>
                        <th id="tab_b"></th>
                        <th id="tab_b"><h4 id="tab-b-n">Будние дни до 18:00</h4></th>
                        <th id="tab_b"><h4 id="tab-b-n">Будние дни после 18:00,<br> выходные, праздничные</h4></th>
                    </tr>
                    </thead>
                    <tbody class="tab-block">
                    <tr>
                        <td id="tab_n_n">Абонемент на 4 часа</td>
                        <td id="tab_n">700 <i class="fa fa-rub" aria-hidden="true"></i></td>
                        <td id="tab_n">1 100 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">Абонемент на 8 часов</td>
                        <td id="tab_n">1 200 <i class="fa fa-rub" aria-hidden="true"></i></td>
                        <td id="tab_n">2 000 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">Абонемент на месяц (безлимит)</td>
                        <td id="tab_n">1 500 <i class="fa fa-rub" aria-hidden="true"></i></td>
                        <td id="tab_n">2 300 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">Абонемент на 3 месяца (безлимит)</td>
                        <td id="tab_n">4 000 <i class="fa fa-rub" aria-hidden="true"></i></td>
                        <td id="tab_n">6 000 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">Абонемент на 6 месяцев (безлимит)</td>
                        <td id="tab_n">7 500 <i class="fa fa-rub" aria-hidden="true"></i></td>
                        <td id="tab_n">11 500 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">Абонемент на 1 год (безлимит)</td>
                        <td id="tab_n">12 000 <i class="fa fa-rub" aria-hidden="true"></i></td>
                        <td id="tab_n">18 000 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

<!--                    <tr>
                        <td></td>
                        <td><button type="button" class="btn btn-secondary">Купить</button></td>
                        <td><button type="button" class="btn btn-secondary">Купить</button></td>
                    </tr>-->

                    <tr>
                        <td colspan="3"><hr id="cherta_tab"></td>
                    </tr>
                    </tbody>
                </table>



                <table class="table_posit">
                    <caption id="tab-h">Индивидуальные занятия с инструктором</caption>

                    <tbody class="tab-block">
                    <tr>
                        <td id="tab_n_n">1 занятие</td>
                        <td id="tab_n">600 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    

                    <tr>
                        <td id="tab_n_n">4 занятия</td>
                        <td id="tab_n">2 200 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">8 занятий</td>
                        <td id="tab_n">4 200 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <!--<tr>
                    <td></td>
                    <td><button type="button" class="btn btn-secondary">Купить</button></td>
                    </tr>-->

                    <tr>
                        <td colspan="2"><hr id="cherta_tab"></td>
                    </tr>
                    </tbody>
                </table>


                <table class="table_posit">
                    <caption><h3 id="tab-h">Групповые занятия с инструктором</h3>
                        <p id="tab-h-p">(детские группы, акробатика, фристайл)</p>
                    </caption>

                    <tbody class="tab-block">
                    <tr>
                        <td id="tab_n_n">1 занятие</td>
                        <td id="tab_n">400 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">4 занятия</td>
                        <td id="tab_n">1 400 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">8 занятий</td>
                        <td id="tab_n">2 600 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <!--<tr>
                    <td></td>
                    <td><button type="button" class="btn btn-secondary">Купить</button></td>
                    </tr>-->

                    <tr>
                        <td colspan="2"><hr id="cherta_tab"></td>
                    </tr>
                    </tbody>
                </table>


                <table class="table_posit">
                    <caption><h3 id="tab-h">Фриран</h3>
                    </caption>

                    <tbody class="tab-block">
                    <tr>
                        <td id="tab_n_n">1 занятие</td>
                        <td id="tab_n">400 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">8 занятий (месяц)</td>
                        <td id="tab_n">2 000 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <!--<tr>
                    <td></td>
                    <td><button type="button" class="btn btn-secondary">Купить</button></td>
                    </tr>-->

                    <tr>
                        <td colspan="2"><hr id="cherta_tab"></td>
                    </tr>
                    </tbody>
                </table>
                
                 <table class="table_posit">
                    <caption><h3 id="tab-h">Специальные предложения для групп</h3>
                    </caption>

                    <tbody class="tab-block">
                    <tr>
                        <td id="tab_n_n">Детский праздник в Батутном центре (до 12 чел)<br> будние дни с 10-00 до 14-00</td>
                        <td id="tab_n">2х часовая программа / 8000 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <tr>
                        <td id="tab_n_n">Детский праздник в батутном центре (до 12 чел)<br> будние дни после 14-00, выходные</td>
                        <td id="tab_n">2х часовая программа / 10000 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>
                    
                    <tr>
                        <td id="tab_n_n">Урок физкультуры в Батутном Центре (для школьников).<br> Обязательна справка от школьного врача!</td>
                        <td id="tab_n">
                            до 12 человек – 3000 <i class="fa fa-rub" aria-hidden="true"></i>/час,<br>
                            13 - 24 человек – 4000 <i class="fa fa-rub" aria-hidden="true"></i>/час,<br>
                            25 и более человек – 5000 <i class="fa fa-rub" aria-hidden="true"></i>/час
                         </td>
                    </tr>
                    
                    <tr>
                        <td id="tab_n_n">Аренда зала (с инструктором), до 12 человек</td>
                        <td id="tab_n">Первый час – 4500 <i class="fa fa-rub" aria-hidden="true"></i><br>
                                        Последующие часы – 3500 <i class="fa fa-rub" aria-hidden="true"></i>/час
 </td>
                    </tr>
                    
                    <tr>
                        <td id="tab_n_n">Фотосъёмка детского праздника</td>
                        <td id="tab_n">от 500 <i class="fa fa-rub" aria-hidden="true"></i></td>
                    </tr>

                    <!--<tr>
                    <td></td>
                    <td><button type="button" class="btn btn-secondary">Купить</button></td>
                    </tr>-->

                    <tr>
                        <td colspan="2"><hr id="cherta_tab"></td>
                    </tr>
                    </tbody>
                </table>



                <div class="container">
                    <div class="row" id="tab_text_down" style="font-weight: normal;">
                <p class="chil_text_2"><b>ВНИМАНИЕ: смена всех тарифов осуществляется в 18:00!</b></p>
                <p class="chil_text_2">Занятие длится 1 час. Начало текущего занятия и завершение предыдущего происходит в начале часа.</p>
                <p class="chil_text_2">Дети до 5 лет допускаются к прыжкам в присутствии родителя и инструктора в специально отведённое время. Подробности у администратора.</p>
                <p class="chil_text_2">Дети до 14 лет допускаются к прыжкам на батуте ТОЛЬКО в присутствии родителя либо при занятии с инструктором.</p>
                <p class="chil_text_2">Посетители до 18 лет допускаются к прыжкам на батуте при предъявлении письменного разрешения от родителей на посещение Батутного Центра.</p>
                <p class="chil_text_2">Обязательно наличие спортивной формы. Посетители, отказывающиеся использовать спортивную форму во время прыжков на батуте, не будут допущены к занятию. Даже при наличии предварительной брони.</p>
                <p class="chil_text_2">У нас есть раздевалки со шкафчиками и душевыми, вай-фай и музыка.</p>
                <p class="chil_text_2">При входе надевайте бахилы.</p>
                <p class="chil_text_2"><strong>Добро пожаловать в Батутный Центр Level UP!</strong></p>
                
                
                    </div>
                </div>


            </div>
        </div>
    </div>
    <!-- Конец таблицы -->

    <!-- Специальные предложения -->
    <div class="special_offer">
        <div class="container">
            <div class="row">
                <table class="table_posit">
                    <caption><h3 id="tab-h_invers">Подарочные карты</h3>
                    </caption>
                    <thead class="tab-block-b">

                    </thead>
                    <tbody class="tab-block">
                    <tr>
                        <td id="tab_n_n_invers">ВЗРОСЛЫЙ + РЕБЕНОК (занятие с инструктором)</td>
                        <td id="tab_n_invers"><button type="button" class="btn btn-secondary" onclick="window.location.href='https://pay.erpico.ru/pay.php?refId=3&partner=1&amount=120000&text=Подарочный сертификат LevelUp на взрослого и ребенка (с инструктором)'">1 200 <i class="fa fa-rub" aria-hidden="true"></i></button></td>
                    </tr>
                    <tr>
                        <td id="tab_n_n_invers">ОДИН ВЗРОСЛЫЙ (занятие с инструктором)</td>
                        <td id="tab_n_invers"><button type="button" class="btn btn-secondary" onclick="window.location.href='https://pay.erpico.ru/pay.php?refId=4&partner=1&amount=80000&text=Подарочный сертификат LevelUp на одного взрослого (с инструктором)'">800 <i class="fa fa-rub" aria-hidden="true"></i></button></td>
                    </tr>
                    <tr>
                        <td id="tab_n_n_invers">ВЗРОСЛЫЙ + РЕБЕНОК (свободное посещение)</td>
                        <td id="tab_n_invers"><button type="button" class="btn btn-secondary" onclick="window.location.href='https://pay.erpico.ru/pay.php?refId=5&partner=1&amount=60000&text=Подарочный сертификат LevelUp на взрослого и ребенока (свободное посещение)'">600 <i class="fa fa-rub" aria-hidden="true"></i></button></td>
                    </tr>
                    <tr>
                        <td id="tab_n_n_invers">ОДИН ВЗРОСЛЫЙ (свободное посещение)</td>
                        <td id="tab_n_invers"><button type="button" class="btn btn-secondary" onclick="window.location.href='https://pay.erpico.ru/pay.php?refId=6&partner=1&amount=40000&text=Подарочный сертификат LevelUp на одного взрослого (свободное посещение)'">400 <i class="fa fa-rub" aria-hidden="true"></i></button></td>
                    </tr>


                    </tbody>
                </table>
            </div>
        </div>
    </div>



    <!-- Конец специальные предложения -->