    <!-- Заголовок и контент -->
    <div class="content_price">
        <div class="container">
            <div class="row">
                <h1 class="name_price">Записаться на тренировку</h1>
                <span class="cherta_ind hidden-xs"></span>
            </div>
        </div>
    </div>


    <!-- Контент -->
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <!--/ Codrops top bar -->
                <section class="main">
                    <div class="custom-calendar-wrap">
                        <div id="custom-inner" class="custom-inner">
                            <div class="custom-header clearfix">
                                <nav>
                                    <span id="custom-prev" class="custom-prev"></span>
                                    <span id="custom-next" class="custom-next"></span>
                                </nav>
                                <h2 id="custom-month" class="custom-month"></h2>
                                <h3 id="custom-year" class="custom-year"></h3>
                            </div>
                            <div id="calendar" class="fc-calendar-container"></div>
                        </div>
                    </div>
                </section>

            </div>

            <div class="col-lg-7" id="datatable_record">
            </div>
        </div>
        <div class="text rules">
            <ul><li>Дети до 5 лет допускаются к прыжкам в присутствии родителя и инструктора в специально отведённое время. Подробности у администратора.
		<li>Дети до 14 лет допускаются к прыжкам на батуте ТОЛЬКО в присутствии родителя либо при занятии с инструктором.
		<li>Посетители до 18 лет допускаются к прыжкам на батуте при предъявлении письменного разрешения от родителей на посещение Батутного Центра.
		<li>Обязательно наличие спортивной формы. Посетители, отказывающиеся использовать спортивную форму во время прыжков на батуте, не будут допущены к занятию. Даже при наличии предварительной брони.
		<li>У нас есть раздевалки со шкафчиками и душевыми, вай-фай и музыка.
		<li>При входе надевайте бахилы.
	     </ul>
	     <p class="write_text rules">Записываясь на занятие, вы соглашаетесь с <a href="/docs/LevelUp_rules.pdf">правилами посещения батутного центра Level Up</a>.<br/>Пожалуйста, не забудьте ознакомиться с ними.</p>
        </div>
    </div>
    <!-- Конец контента-->


    <br>
    <!-- Окно записи на тренировку -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="formx">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Записаться на тренировку</h4>
                    </div>
                    <div class="modal-body">
                        <p class="error error_name hidden">Представьтесь, пожалуйста.</p>
                        <p class="error error_error hidden"></p>
                        <p class="done error_name hidden"><b>Ваша запись успешно добавлена!</b></p>

                        <div class="form-group">
                            <label for="inputName">Имя</label>
                            <input name="name" type="name" class="form-control" id="inputName" placeholder="Имя" value="<?=((isset($_COOKIE['save']) && $_COOKIE['save']==1 && isset($_COOKIE['name'])) ? $_COOKIE['name'] : "") ?>">
                            <input type="hidden" name="setUser" type="name" class="form-control" value="1">
                            <input type="hidden" name="setRecord" type="name" class="form-control" value="1">
                            <input type="hidden" name="schedule_id" type="name" class="form-control" value="0" id="schedule_id">
                            <input type="hidden" name="schedule_date" type="name" class="form-control" value="0" id="schedule_date">
                            <input type="hidden" name="schedule_time" type="name" class="form-control" value="0" id="schedule_time">
                        </div>

                        <div class="form-group">
                            <label for="inputSurname">Фамилия</label>
                            <input name="last_name" type="name" class="form-control" id="inputLastname" placeholder="Фамилия" value="<?=((isset($_COOKIE['save']) && $_COOKIE['save']==1 && isset($_COOKIE['last_name'])) ? $_COOKIE['last_name'] : "") ?>">
                        </div>
                        <p class="error error_userphone hidden">Пожалуйста, введите номер телефона.</p>
                        <div class="form-group">
                            <label for="inputPhone">Телефон</label>
                            <input name="phone" type="phone" class="form-control" id="inputPhone" placeholder="Телефон*" value="<?=((isset($_COOKIE['save']) && $_COOKIE['save']==1 && isset($_COOKIE['phone'])) ? $_COOKIE['phone'] : "") ?>">
                        </div>

                        <p class="error error_count hidden"></p>
                        <div class="form-group">
                            <label for="inputCount">Количество человек</label>
                            <select name="cnt" type="count" class="form-control" id="inputCount" placeholder="Количество человек">
<?php 

for ($i = 1; $i <= 10; $i++) { print "<option ".($i == 1 ? "selected" : "")." value=\"$i\">$i</option>"; } ?>
                            </select>
                        </div>
                        <div class="mycheckbox">
                            <input type="checkbox" name="rules" id="inputRules"><label for="inputRules">&nbsp;&nbsp;Я ознакомился и согласен с <span class="rules"><a href="/docs/LevelUp_rules.pdf" target=_blank class="rules">правилами посещения</a></span></label>	                    
                        </div>
                        <div class="mycheckbox">
                            <input type="checkbox" name="save" id="inputSave" <?=((isset($_COOKIE['save']) && $_COOKIE['save']==1) ? "checked" : "") ?>><label for="inputSave">&nbsp&nbspСохранить данные</label>
                        </div>
                        <div class="mycheckbox" style="font: 14px 'Calibri', Arial">
                          Указание достоверной информации (Имя, Фамилия, номер телефона) является обязательным условием оформления записи на посещение Батутного Центра.<br/>
                          Записи, не содержащие достоверной информации, будут аннулированы и удалены. Спасибо за понимание.
                        </div>                        
                    </div>
                    <div class="modal-footer">
                    
                        <input type="button" id="record" class="btn btn-secondary" value="Записаться">
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
    <div class="modal recdel">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="formd">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Удалить запись на тренировку</h4>
                    </div>
                    <div class="modal-body">
                        <p class="error error_userphone del hidden">Для удаления записи введите номер телефона.</p>
                        <p class="error error_userphone undel hidden">Введен неверный номер телефона.</p>
                        <p class="done error_userphone undel hidden"><b>Ваша запись успешно удалена!</b></p>
                        <div class="form-group">
                            <label for="inputDelPhone">Телефон</label>
                            <input name="phone" type="phone" class="form-control" id="inputDelPhone" placeholder="Телефон*">
                            <input type="hidden" name="record_id" type="name" id="inputRecord" class="form-control" value="0">
                        </div>

                    </div>
                    <div class="modal-footer">

                        <input type="button" id="recorddel" class="btn btn-secondary" value="Удалить">
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <!-- Конец окна записи на тренировку -->


    <!-- Специальные предложения -->
    <!-- Конец специальные предложения -->