<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>LevelUp Батутный центр Ярославль</title>
    <meta name="keywords" content="батутный центр в ярославле,батутный центр в казармах,батутный центр левел ап,левел ап,level up,прыжки на батуте,попрыгать на батуте в ярослевле,батутный центр,батут,прыжок,зал,полёт,свобода,сальто,трюки,праздник,эмоции,спорт,активный,отдых,акробатика,фристайл,вейкборд,сноуборд,ньюскул,лыжи,горные,растяжка,гимнастика,фриран,паркур,трейсер,разминка,зарядка,клуб,спортзал,спортклуб,евротрамп,акроспорт,минитрамп,лонжа,сальто,мортале,кульбит,рондат,физкультура,здоровье,вейкпарк,лебёдка,трамплин,пляж,кайт,сёрф,сёрфинг,кайтинг,скалодром,альпинизм,кроссфит,винт,полвинта,корк,даблкорк,триплкорк,родео,бэкфлип,фронтфлип"/>    
    <meta name="description" content="Батутный центр в Ярославле - у  нас Вы можете попрыгать! Прыжки на батуте дарят удивительное чувство бодрости, прилива сил и энергии."/>
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <!-- Bootstrap -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/font-awesome.css" rel="stylesheet">

    <? if ($page == 'schedule'): ?>
        <link rel="stylesheet" type="text/css" href="/css/calendar.css"/>
        <link rel="stylesheet" type="text/css" href="/css/custom_2.css"/>
    <? endif ?>
    <link rel="shortcut icon" href="/img/ico.ico">

    <meta property="og:title" content="LevelUp Батутный центр Ярославль" />
    <meta property="og:url" content="http://levelup76.ru/" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="http://levelup76.ru/img/levelup.png" />
    <meta property="og:description" content="Батутный центр в Ярославле - у  нас Вы можете попрыгать! Прыжки на батуте дарят удивительное чувство бодрости, прилива сил и энергии." />
    <meta name="twitter:card" content="summary">
    <meta name="twitter:url" content="http://levelup76.ru/">
    <meta name="twitter:title" content="LevelUp Батутный центр Ярославль"/>
    <meta name="twitter:description" content="Батутный центр в Ярославле - у  нас Вы можете попрыгать! Прыжки на батуте дарят удивительное чувство бодрости, прилива сил и энергии." />
    <meta name="twitter:image" content="http://levelup76.ru/img/levelup.png"/>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="wrapper">

    <a href="#" class="scrollup">Наверх</a>


    <!-- Основное меню -->

    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#responsive-menu">
                    <span class="sr-only">Открыть меню</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><img src="/img/logo.png" height="110" width="453"
                                                               class="hidden-xs hidden-sm hidden-md"
                                                               class="img-responsive" alt="Responsive image"></a>
                <a class="navbar-brand" href="/"><img src="/img/logo_2.png" height="61" width="250"
                                                               class="visible-xs hidden-sm hidden-md"
                                                               class="img-responsive" alt="Responsive image"></a>
                <a class="navbar-brand" href="/"><img src="/img/logo_3.png" height="61" width="40"
                                                               class="visible-sm visible-md hidden-xs item-img"
                                                               class="img-responsive" alt="Responsive image"></a>


            </div>
            <div class="navbar-collapse collapse" id="responsive-menu">
                <ul id="menu-main-menu" class="nav navbar-nav navbar-right">
                    <?php foreach($menu as $url => $title) {
                        print "<li id=\"\" class=\"item-menu ".($url == $page ? "active" : "")."\"><a href=\"/$url\">$title</a></li>";
                      }
                    ?>
                </ul>

            </div>
        </div>
    </div>
        <!-- Конец основного меню -->

        <?=$content?>

<!-- Подвал -->
<footer>

    <div class="container">
        <div class="row foot_content">

            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12 f_cont">
                <h class="footer_bold">Мы в социальных сетях</h>
                <br><br>
                         <span class="vac">
                                <ul class="social-network social-circle">
                                    <li><a href="#" target="_blank" class="ico icoVK" title="VK"><i
                                                class="fa fa-vk"></i></a></li>

                                    <li><a href="#" target="_blank"
                                           class="ico icoInstagram" title="Instagram"><i
                                                class="fa fa-instagram"></i></a></li>

                                    <li><a href="#" target="_blank"
                                           class="ico icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a>
                                    </li>
                                </ul>
                         </span>
            </div>

           <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12 f_cont">
                <h class="footer_bold">Наши партнеры</h>
                <div class="part_img"> 
                <a href="http://top-drive.org/" target="_blank">
                    <img style="border: 0px;" onmouseover="this.src='/img/topdrive-logo-skal.png';"
                         onmouseout="this.src='/img/topdrive-logo-skal_activ.png';"
                         alt="" src="/img/topdrive-logo-skal_activ.png" width="148" height="69">
                </a>
                
            &nbsp;&nbsp; &nbsp;&nbsp;
                <a href="http://yarbassein.ru" target="_blank">
                    <img style="border: 0px;" onmouseover="this.src='/img/topdrive-logo-bas.png';"
                         onmouseout="this.src='/img/topdrive-logo-bas_activ.png';"
                         alt="" src="/img/topdrive-logo-bas_activ.png" width="86" height="69">
                </a>
                </div>
            </div>
           
           
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12 f_cont">
                <h class="footer_bold">Режим работы СОК</h>
                <br><br>
                <span class="vac">Ежедневно с 08:00 до 23:00</span>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12 f_cont">
                <h class="footer_bold">Наши контакты</h>
                <br><br>
                         <span class="vac">г. Ярославль, ул. Свободы, д. 46/2
                            <br>(территория Вознесенских Казарм)
                            <br>тел. +7 (4852) 73-99-74
                            <br>e-mail: yarbassein@yandex.ru</span>
            </div>
            
            

        </div>
    </div>


   <!--  <div class="container">
        <div class="row foot_content">
            <div class="col-lg-4 col-sm-6 f_cont">
                <h class="footer_bold">Наши партнеры</h>
                <br>
            </div>
            <div class="col-lg-4 col-sm-6 f_cont"></div>
            <div class="col-lg-4 col-sm-6 f_cont"></div>
        </div>
    </div>

    <div class="container">

        <div class="row partners" data-columns>

            <div class="part_img">
                <a href="http://top-drive.org/" target="_blank">
                    <img style="border: 0px;" onmouseover="this.src='/img/topdrive-logo-skal.png';"
                         onmouseout="this.src='/img/topdrive-logo-skal_activ.png';"
                         alt="" src="/img/topdrive-logo-skal_activ.png" width="148" height="69">
                </a>
            </div>
            <div class="part_img">
                <a href="http://levelup76.ru" target="_blank">
                    <img style="border: 0px;" onmouseover="this.src='/img/levelup.png';"
                         onmouseout="this.src='/img/levelup_active.png';"
                         alt="" src="/img/levelup_active.png" width="79" height="126">
                </a>
            </div>
      <div class="part_img">
                <a href="http://yarvzlet.ru/" target="_blank">
                    <img style="border: 0px;" onmouseover="this.src='/img/vzlet.png';"
                         onmouseout="this.src='/img/vzlet_activ.png';"
                         alt="" src="/img/vzlet_activ.png" width="148" height="120">
                </a>
            </div>
            <div class="part_img">
                <a href="http://grizzly76.ru/" target="_blank">
                    <img style="border: 0px;" onmouseover="this.src='/img/grizzly.png';"
                         onmouseout="this.src='/img/grizzly_active.png';"
                         alt="" src="/img/grizzly_active.png" width="102" height="129">
                </a>
            </div>
            <div class="part_img">
                <a href="http://yarparaplan.jimdo.com/" target="_blank">
                    <img style="border: 0px;" onmouseover="this.src='/img/yarpilot.png';"
                         onmouseout="this.src='/img/yarpilot_active.png';"
                         alt="" src="/img/yarpilot_active.png" width="135" height="111">
                </a>
            </div>
            <div class="part_img">
                <a href="http://jamaica76.ru/" target="_blank">
                    <img style="border: 0px;" onmouseover="this.src='/img/jamaica.png';"
                         onmouseout="this.src='/img/jamaica_active.png';"
                         alt="" src="/img/jamaica_active.png" width="135" height="62">
                </a>
            </div> 
        </div>

    </div>-->


    <div class="container">
        <div class="row foot_content">
            <div class="col-lg-8 col-sm-6 f_cont">
                <p id="company_f">
                    &copy; ООО “Топ Драйв” 2016 / Тел.:+7 (4852) 73-99-74 <span id="company">&Iota; Разработка:<a
                            href="http://erpico.ru/" target="_blank"> Erpico</a></span>
                </p>
            </div>
            <div class="col-lg-4 col-sm-6 f_cont vac">
                <p>
                            <span id="vacancy"><a href="/vacancy/">Вакансии</a>&nbsp;&nbsp;
                            <a href="/vacancy/#parthers">Сотрудничество</a></span>
                </p>
            </div>
        </div>


    </div>


</footer>


</div>


<script src="/js/salvattore.min.js"></script>
<script type="text/javascript" src="/js/sessvars.js"></script>
<? if ($page == 'schedule'): ?>
    <script type="text/javascript" src="/js/jquery.calendario.js"></script>
    <script src="/js/jquery.maskedinput.min.js" type="text/javascript"></script>
    <script src="/js/modernizr.custom.63321.js"></script>
    <script type="text/javascript" src="/js/data.js"></script>
<? endif ?>
<!-- Yandex.Metrika counter -->
<script type="text/javascript"> (function (d, w, c) {
        (w[c] = w[c] || []).push(function () {
            try {
                w.yaCounter37193835 = new Ya.Metrika({
                    id: 37193835,
                    clickmap: true,
                    trackLinks: true,
                    accurateTrackBounce: true,
                    webvisor: true,
                    trackHash: true
                });
            } catch (e) {
            }
        });
        var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () {
            n.parentNode.insertBefore(s, n);
        };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";
        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else {
            f();
        }
    })(document, window, "yandex_metrika_callbacks");
    setTimeout(function () {
        $('.fc-today').click(), 100
    });

</script>

<noscript>
    <div><img src="https://mc.yandex.ru/watch/37193835" style="position:absolute; left:-9999px;" alt=""/></div>
</noscript> <!-- /Yandex.Metrika counter -->

<!--<script type="text/javascript">
    !function (e, t, a) {
        var r = e.createElement("script");
        r.type = "text/javascript", r.async = !0, r.src = "htt" + "ps://soc" + "gate.ru/?id=" + t + "&guid=" + a + "&e79.js";
        var c = e.getElementsByTagName("script")[0];
        c.parentNode.insertBefore(r, c)
    }(document, "9d7dca13a6593661", "");
</script>-->
</body>
</html>